/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#include "CertificateAddedContainer.h"

asn_TYPE_member_t asn_MBR_CertificateAddedContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateAddedContainer, reportedMessage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EtsiTs103097Data,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reportedMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateAddedContainer, reportedCertificate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EtsiTs103097Certificate,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reportedCertificate"
		},
};
static const ber_tlv_tag_t asn_DEF_CertificateAddedContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CertificateAddedContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportedMessage */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reportedCertificate */
};
asn_SEQUENCE_specifics_t asn_SPC_CertificateAddedContainer_specs_1 = {
	sizeof(struct CertificateAddedContainer),
	offsetof(struct CertificateAddedContainer, _asn_ctx),
	asn_MAP_CertificateAddedContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CertificateAddedContainer = {
	"CertificateAddedContainer",
	"CertificateAddedContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_CertificateAddedContainer_tags_1,
	sizeof(asn_DEF_CertificateAddedContainer_tags_1)
		/sizeof(asn_DEF_CertificateAddedContainer_tags_1[0]), /* 1 */
	asn_DEF_CertificateAddedContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_CertificateAddedContainer_tags_1)
		/sizeof(asn_DEF_CertificateAddedContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CertificateAddedContainer_1,
	2,	/* Elements count */
	&asn_SPC_CertificateAddedContainer_specs_1	/* Additional specs */
};

