/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CertificateAddedContainer_H_
#define	_CertificateAddedContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs103097Data.h"
#include "EtsiTs103097Certificate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateAddedContainer */
typedef struct CertificateAddedContainer {
	EtsiTs103097Data_t	 reportedMessage;
	EtsiTs103097Certificate_t	 reportedCertificate;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateAddedContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateAddedContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_CertificateAddedContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateAddedContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateAddedContainer_H_ */
#include "asn_internal.h"
