/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CertificateIncludedContainer_H_
#define	_CertificateIncludedContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs103097Data.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateIncludedContainer */
typedef struct CertificateIncludedContainer {
	EtsiTs103097Data_t	 reportedMessage;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateIncludedContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateIncludedContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_CertificateIncludedContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateIncludedContainer_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateIncludedContainer_H_ */
#include "asn_internal.h"
