/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DetectionLevel_H_
#define	_DetectionLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DetectionLevel {
	DetectionLevel_level	= 1
} e_DetectionLevel;

/* DetectionLevel */
typedef long	 DetectionLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DetectionLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DetectionLevel;
asn_struct_free_f DetectionLevel_free;
asn_struct_print_f DetectionLevel_print;
asn_constr_check_f DetectionLevel_constraint;
ber_type_decoder_f DetectionLevel_decode_ber;
der_type_encoder_f DetectionLevel_encode_der;
xer_type_decoder_f DetectionLevel_decode_xer;
xer_type_encoder_f DetectionLevel_encode_xer;
oer_type_decoder_f DetectionLevel_decode_oer;
oer_type_encoder_f DetectionLevel_encode_oer;
per_type_decoder_f DetectionLevel_decode_uper;
per_type_encoder_f DetectionLevel_encode_uper;
per_type_decoder_f DetectionLevel_decode_aper;
per_type_encoder_f DetectionLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DetectionLevel_H_ */
#include "asn_internal.h"
