/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DetectionReferenceCAM_H_
#define	_DetectionReferenceCAM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DetectionLevel.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DetectionReferenceCAM */
typedef struct DetectionReferenceCAM {
	DetectionLevel_t	 detectionLevelCAM;
	OCTET_STRING_t	 semanticDetectionErrorCodeCAM;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DetectionReferenceCAM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DetectionReferenceCAM;
extern asn_SEQUENCE_specifics_t asn_SPC_DetectionReferenceCAM_specs_1;
extern asn_TYPE_member_t asn_MBR_DetectionReferenceCAM_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DetectionReferenceCAM_H_ */
#include "asn_internal.h"
