/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_EvidenceContainer_H_
#define	_EvidenceContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MessageEvidenceContainer;
struct SenderInfoContainer;
struct SenderSensorContainer;

/* EvidenceContainer */
typedef struct EvidenceContainer {
	struct MessageEvidenceContainer	*reportedMessageContainer;	/* OPTIONAL */
	struct MessageEvidenceContainer	*neighbourMessageContainer;	/* OPTIONAL */
	struct SenderInfoContainer	*senderInfoContainer;	/* OPTIONAL */
	struct SenderSensorContainer	*senderSensorContainer;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EvidenceContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EvidenceContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_EvidenceContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_EvidenceContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MessageEvidenceContainer.h"
#include "SenderInfoContainer.h"
#include "SenderSensorContainer.h"

#endif	/* _EvidenceContainer_H_ */
#include "asn_internal.h"
