/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "asn1/IEEE1609dot2BaseTypes_MD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Latitude1609_H_
#define	_Latitude1609_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NinetyDegreeInt.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Latitude1609 */
typedef NinetyDegreeInt_t	 Latitude1609_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Latitude1609_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Latitude1609;
asn_struct_free_f Latitude1609_free;
asn_struct_print_f Latitude1609_print;
asn_constr_check_f Latitude1609_constraint;
ber_type_decoder_f Latitude1609_decode_ber;
der_type_encoder_f Latitude1609_encode_der;
xer_type_decoder_f Latitude1609_decode_xer;
xer_type_encoder_f Latitude1609_encode_xer;
oer_type_decoder_f Latitude1609_decode_oer;
oer_type_encoder_f Latitude1609_encode_oer;
per_type_decoder_f Latitude1609_decode_uper;
per_type_encoder_f Latitude1609_encode_uper;
per_type_decoder_f Latitude1609_decode_aper;
per_type_encoder_f Latitude1609_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Latitude1609_H_ */
#include "asn_internal.h"
