/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_MisbehaviorReport_H_
#define	_MisbehaviorReport_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Version.h"
#include "ReportMetadataContainer.h"
#include "ReportContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MisbehaviorReport */
typedef struct MisbehaviorReport {
	Version_t	 version;
	ReportMetadataContainer_t	 reportMetadataContainer;
	ReportContainer_t	 reportContainer;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MisbehaviorReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MisbehaviorReport;

#ifdef __cplusplus
}
#endif

#endif	/* _MisbehaviorReport_H_ */
#include "asn_internal.h"
