/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_MisbehaviorTypeContainer_H_
#define	_MisbehaviorTypeContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SecurityDetection.h"
#include "SemanticDetection.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MisbehaviorTypeContainer_PR {
	MisbehaviorTypeContainer_PR_NOTHING,	/* No components present */
	MisbehaviorTypeContainer_PR_securityDetection,
	MisbehaviorTypeContainer_PR_semanticDetection
	/* Extensions may appear below */
	
} MisbehaviorTypeContainer_PR;

/* MisbehaviorTypeContainer */
typedef struct MisbehaviorTypeContainer {
	MisbehaviorTypeContainer_PR present;
	union MisbehaviorTypeContainer_u {
		SecurityDetection_t	 securityDetection;
		SemanticDetection_t	 semanticDetection;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MisbehaviorTypeContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MisbehaviorTypeContainer;
extern asn_CHOICE_specifics_t asn_SPC_MisbehaviorTypeContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_MisbehaviorTypeContainer_1[2];
extern asn_per_constraints_t asn_PER_type_MisbehaviorTypeContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MisbehaviorTypeContainer_H_ */
#include "asn_internal.h"
