/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_OmittedReportsNumber_H_
#define	_OmittedReportsNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OmittedReportsNumber {
	OmittedReportsNumber_oneReport	= 1
} e_OmittedReportsNumber;

/* OmittedReportsNumber */
typedef long	 OmittedReportsNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_OmittedReportsNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_OmittedReportsNumber;
asn_struct_free_f OmittedReportsNumber_free;
asn_struct_print_f OmittedReportsNumber_print;
asn_constr_check_f OmittedReportsNumber_constraint;
ber_type_decoder_f OmittedReportsNumber_decode_ber;
der_type_encoder_f OmittedReportsNumber_encode_der;
xer_type_decoder_f OmittedReportsNumber_decode_xer;
xer_type_encoder_f OmittedReportsNumber_encode_xer;
oer_type_decoder_f OmittedReportsNumber_decode_oer;
oer_type_encoder_f OmittedReportsNumber_encode_oer;
per_type_decoder_f OmittedReportsNumber_decode_uper;
per_type_encoder_f OmittedReportsNumber_encode_uper;
per_type_decoder_f OmittedReportsNumber_decode_aper;
per_type_encoder_f OmittedReportsNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _OmittedReportsNumber_H_ */
#include "asn_internal.h"
