/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_RelatedReportContainer_H_
#define	_RelatedReportContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"
#include "OmittedReportsNumber.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RelatedReportContainer */
typedef struct RelatedReportContainer {
	IA5String_t	 relatedReportID;
	OmittedReportsNumber_t	 omittedReportsNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RelatedReportContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelatedReportContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_RelatedReportContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_RelatedReportContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RelatedReportContainer_H_ */
#include "asn_internal.h"
