/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#include "ReportContainer.h"

asn_TYPE_member_t asn_MBR_ReportContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportContainer, reportedMessageContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReportedMessageContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reportedMessageContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportContainer, misbehaviorTypeContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MisbehaviorTypeContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"misbehaviorTypeContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct ReportContainer, evidenceContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EvidenceContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"evidenceContainer"
		},
};
static const int asn_MAP_ReportContainer_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ReportContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReportContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportedMessageContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* misbehaviorTypeContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* evidenceContainer */
};
asn_SEQUENCE_specifics_t asn_SPC_ReportContainer_specs_1 = {
	sizeof(struct ReportContainer),
	offsetof(struct ReportContainer, _asn_ctx),
	asn_MAP_ReportContainer_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ReportContainer_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReportContainer = {
	"ReportContainer",
	"ReportContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ReportContainer_tags_1,
	sizeof(asn_DEF_ReportContainer_tags_1)
		/sizeof(asn_DEF_ReportContainer_tags_1[0]), /* 1 */
	asn_DEF_ReportContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReportContainer_tags_1)
		/sizeof(asn_DEF_ReportContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ReportContainer_1,
	3,	/* Elements count */
	&asn_SPC_ReportContainer_specs_1	/* Additional specs */
};

