/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ReportedMessageContainer_H_
#define	_ReportedMessageContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CertificateIncludedContainer.h"
#include "CertificateAddedContainer.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportedMessageContainer_PR {
	ReportedMessageContainer_PR_NOTHING,	/* No components present */
	ReportedMessageContainer_PR_certificateIncludedContainer,
	ReportedMessageContainer_PR_certificateAddedContainer
} ReportedMessageContainer_PR;

/* ReportedMessageContainer */
typedef struct ReportedMessageContainer {
	ReportedMessageContainer_PR present;
	union ReportedMessageContainer_u {
		CertificateIncludedContainer_t	 certificateIncludedContainer;
		CertificateAddedContainer_t	 certificateAddedContainer;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportedMessageContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportedMessageContainer;
extern asn_CHOICE_specifics_t asn_SPC_ReportedMessageContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportedMessageContainer_1[2];
extern asn_per_constraints_t asn_PER_type_ReportedMessageContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportedMessageContainer_H_ */
#include "asn_internal.h"
