/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SecurityDetection_H_
#define	_SecurityDetection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityDetection */
typedef struct SecurityDetection {
	OCTET_STRING_t	 securityDetectionErrorCode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityDetection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityDetection;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityDetection_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityDetection_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityDetection_H_ */
#include "asn_internal.h"
