/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SemanticDetection_H_
#define	_SemanticDetection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DetectionReferenceCAM.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemanticDetection_PR {
	SemanticDetection_PR_NOTHING,	/* No components present */
	SemanticDetection_PR_semanticDetectionReferenceCAM
	/* Extensions may appear below */
	
} SemanticDetection_PR;

/* SemanticDetection */
typedef struct SemanticDetection {
	SemanticDetection_PR present;
	union SemanticDetection_u {
		DetectionReferenceCAM_t	 semanticDetectionReferenceCAM;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SemanticDetection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SemanticDetection;
extern asn_CHOICE_specifics_t asn_SPC_SemanticDetection_specs_1;
extern asn_TYPE_member_t asn_MBR_SemanticDetection_1[1];
extern asn_per_constraints_t asn_PER_type_SemanticDetection_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SemanticDetection_H_ */
#include "asn_internal.h"
