/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SenderInfoContainer_H_
#define	_SenderInfoContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationType.h"
#include "ReferencePosition.h"
#include "Heading.h"
#include "Speed.h"
#include "DriveDirection.h"
#include "VehicleLength.h"
#include "VehicleWidth.h"
#include "LongitudinalAcceleration.h"
#include "Curvature.h"
#include "YawRate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SenderInfoContainer */
typedef struct SenderInfoContainer {
	StationType_t	 stationType;
	ReferencePosition_t	 referencePosition;
	Heading_t	 heading;
	Speed_t	 speed;
	DriveDirection_t	 driveDirection;
	VehicleLength_t	 vehicleLength;
	VehicleWidth_t	 vehicleWidth;
	LongitudinalAcceleration_t	 longitudinalAcceleration;
	Curvature_t	 curvature;
	YawRate_t	 yawRate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SenderInfoContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SenderInfoContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SenderInfoContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SenderInfoContainer_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _SenderInfoContainer_H_ */
#include "asn_internal.h"
