/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTr103460MisbehaviorReportMessage"
 * 	found in "asn1/TR103460v211-MisbehaviorReport.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SenderSensorContainer_H_
#define	_SenderSensorContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SenderSensorChoice;

/* SenderSensorContainer */
typedef struct SenderSensorContainer {
	A_SEQUENCE_OF(struct SenderSensorChoice) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SenderSensorContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SenderSensorContainer;
extern asn_SET_OF_specifics_t asn_SPC_SenderSensorContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SenderSensorContainer_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SenderSensorChoice.h"

#endif	/* _SenderSensorContainer_H_ */
#include "asn_internal.h"
